### ISSUE TITLE
Once you have called dispose() on a GroupedToggleController, it can no longer be used.

### ISSUE THREAD

**Issue by kimmy-wang** [meetleev/flutter_grouped_scroll_view#3]
```
[log] A GroupedToggleController was used after being disposed.
Once you have called dispose() on a GroupedToggleController, it can no longer be used.
      #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:147:9)
      #1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:154:6)
      #2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:302:27)
      #3      _ChatFilesScreenState.dispose (package:expert_planet/modules/message/views/chat_files_page.dart:120:23)
      #4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5105:11)
      #5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1917:13)
      #6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #31     List.forEach (dart:core-patch/growable_array.dart:416:8)
      #32     SliverMultiBoxAdaptorElement.visitChildren (package:flutter/src/widgets/sliver.dart:1607:52)
      #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #35     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #41     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
      #42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #47     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #53     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #59     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #89     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #98     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
      #99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #103    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #108    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #109    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #111    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #112    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #114    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #115    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #116    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #117    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #118    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #119    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #120    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #121    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #122    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #123    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #124    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #125    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #126    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #127    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #128    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #129    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #130    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #131    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #132    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #133    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #134    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #135    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #136    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #137    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #138    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #139    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #140    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #141    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #142    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #143    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #144    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #145    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #146    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #147    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #148    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #149    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #150    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #151    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #152    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #153    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #154    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #155    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #156    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #157    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #158    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #159    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #160    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #161    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #162    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #163    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #164    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #165    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #166    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #167    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #168    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #169    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #170    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
      #171    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #172    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #173    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #174    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #175    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #176    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #177    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #178    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #179    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #180    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #181    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #182    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #183    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #184    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #185    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #186    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #187    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #188    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #189    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #190    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #191    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #192    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #193    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #194    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #195    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #196    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #197    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #198    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #199    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #200    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #201    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #202    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #203    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #204    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #205    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #206    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #207    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #208    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #209    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #210    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #211    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #212    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #213    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #214    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #215    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #216    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #217    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #218    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #219    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #220    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #221    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #222    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #223    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #224    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #225    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #226    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #227    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #228    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #229    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #230    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #231    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #232    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #233    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #234    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #235    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #236    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #237    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #238    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #239    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #240    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #241    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #242    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #243    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #244    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #245    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #246    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #247    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #248    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
      #249    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #250    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #251    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #252    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #253    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #254    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #255    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #256    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
      #257    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
      #258    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
      #259    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
      #260    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1926:25)
      #261    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2523:15)
      #262    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2947:7)
      #263    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:885:19)
      #264    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
      #265    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
      #266    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
      #267    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
      #268    _rootRun (dart:async/zone.dart:1391:13)
      #269    _CustomZone.run (dart:async/zone.dart:1293:19)
      #270    _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
      #271    _invoke (dart:ui/hooks.dart:150:10)
      #272    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
      #273    _drawFrame (dart:ui/hooks.dart:115:31)
```

**Comment by meetleev** [comment]
Dispose is automatically called internally, and there is no need to call it again
